from __future__ import annotations

import urllib.parse

from fastapi import APIRouter, HTTPException

from app.schemas.referral import URGENCY_LABELS, ReferralCard, ReferralRequest

router = APIRouter(prefix="/referral", tags=["referral"])


@router.post("/", response_model=ReferralCard)
async def generate_referral(request: ReferralRequest) -> ReferralCard:
    """POST /referral/ — generate a structured referral card.

    Pure logic — no AI call, no database write.
    Formats WhatsApp and SMS message strings, maps urgency level to label and color.

    The WhatsApp deep link opens wa.me with the pre-formatted message.
    The SMS version is a shortened single-line copy of the same content.
    """
    if request.urgency not in URGENCY_LABELS:
        raise HTTPException(
            status_code=422,
            detail=f"Urgency must be 1–5. Received: {request.urgency}",
        )

    label, color = URGENCY_LABELS[request.urgency]

    # Full WhatsApp message (multi-line, formatted for readability)
    whatsapp_text = (
        f"*REFERRAL CARD — {label.upper()}*\n\n"
        f"*Patient Summary:* {request.patient_summary}\n"
        f"*Clinical Reason:* {request.clinical_reason}\n"
        f"*Facility Needed:* {request.facility_type_needed}\n"
        f"*Referred by:* {request.chw_name}"
        + (f" ({request.chw_location})" if request.chw_location else "")
        + "\n\n"
        f"_This referral was generated by CareVision AI. Verify with clinical staff._"
    )

    # SMS version — abbreviated single line within 160-character budget
    sms_text = (
        f"REFERRAL [{label}]: {request.patient_summary[:60]} | "
        f"Reason: {request.clinical_reason[:40]} | "
        f"CHW: {request.chw_name}"
    )

    whatsapp_link = f"https://wa.me/?text={urllib.parse.quote(whatsapp_text)}"

    return ReferralCard(
        urgency_label=label,
        urgency_color=color,
        patient_summary=request.patient_summary,
        clinical_reason=request.clinical_reason,
        facility_type_needed=request.facility_type_needed,
        referring_chw=request.chw_name,
        whatsapp_message=whatsapp_link,
        sms_message=sms_text,
    )
